export type StageId = "application" | "framework" | "runtime" | "model";
export type TrendSignal = "new" | "rising";

export type LandscapeProject = {
  id: string;
  repo: string;
  owner: string;
  name: string;
  description: string;
  stars: number;
  contributors: number | null;
  forks: number;
  openIssues: number;
  license: string;
  openrank: number | null;
  participants: number | null;
  language: string;
  createdAt: string;
  pushedAt: string;
  selectionReason: string;
  selectionCaveat: string;
  landscapeAction: "keep" | "add";
  trendSignals: TrendSignal[];
  trendSignalReason: string;
  topics: string[];
  categories: string[];
  trend: Array<number | null>;
  stage: StageId;
  zone: string;
};
